language: java
jdk:
    - oraclejdk11
script:
    - ant build
    - sonar-scanner
addons:
  sonarcloud:
    organization: "bfkwong" # the key of the org you chose at step #3
    token: $SONAR_TOKEN # encrypted value of your token